version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: heatmaps-memcached

    redis:
      image: redis:alpine
      container_name: heatmaps-redis

    mysql:
      image: mysql:8.0
      container_name: heatmaps-mysql
      working_dir: /application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=heatmaps
        - MYSQL_USER=heat
        - MYSQL_PASSWORD=maps

    webserver:
      image: nginx:alpine
      container_name: heatmaps-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8889:80"
      links:
       - php-fpm

    php-fpm:
      build:
        context: .
        dockerfile: docker/php-fpm/Dockerfile
      container_name: heatmaps-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini

      links:
        - memcached
        - mysql
        - redis
